apiVersion: v1
kind: Service
metadata:
  name: progettare-app
  namespace: progettare
  labels:
    app.kubernetes.io/name: progettare
spec:
  selector:
    app.kubernetes.io/name: progettare
  ports:
    - name: http
      port: 80
      targetPort: 8080
